version: "3.9"
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=111111
      - MARIADB_DATABASE=lottery_db
      - MARIADB_USER=lottery_user
      - MARIADB_PASSWORD=111111